java -jar res-p0.01.jar data/dblp.txt uic 50 > result/res-dblp-uic-k50.out
java -jar res-p0.01.jar data/dblp.txt uic 45 > result/res-dblp-uic-k45.out
java -jar res-p0.01.jar data/dblp.txt uic 40 > result/res-dblp-uic-k40.out
java -jar res-p0.01.jar data/dblp.txt uic 35 > result/res-dblp-uic-k35.out
java -jar res-p0.01.jar data/dblp.txt uic 30 > result/res-dblp-uic-k30.out
java -jar res-p0.01.jar data/dblp.txt uic 25 > result/res-dblp-uic-k25.out
java -jar res-p0.01.jar data/dblp.txt uic 20 > result/res-dblp-uic-k20.out
java -jar res-p0.01.jar data/dblp.txt uic 15 > result/res-dblp-uic-k15.out
java -jar res-p0.01.jar data/dblp.txt uic 10 > result/res-dblp-uic-k10.out
java -jar res-p0.01.jar data/dblp.txt uic 5 > result/res-dblp-uic-k5.out
java -jar res-p0.01.jar data/dblp.txt uic 1 > result/res-dblp-uic-k1.out
