java -jar degree-p0.01.jar data/cit-HepPh wic 50 > result/degree-hepPh-wic-k50.out
java -jar degree-p0.01.jar data/cit-HepPh wic 45 > result/degree-hepPh-wic-k45.out
java -jar degree-p0.01.jar data/cit-HepPh wic 40 > result/degree-hepPh-wic-k40.out
java -jar degree-p0.01.jar data/cit-HepPh wic 35 > result/degree-hepPh-wic-k35.out
java -jar degree-p0.01.jar data/cit-HepPh wic 30 > result/degree-hepPh-wic-k30.out
java -jar degree-p0.01.jar data/cit-HepPh wic 25 > result/degree-hepPh-wic-k25.out
java -jar degree-p0.01.jar data/cit-HepPh wic 20 > result/degree-hepPh-wic-k20.out
java -jar degree-p0.01.jar data/cit-HepPh wic 15 > result/degree-hepPh-wic-k15.out
java -jar degree-p0.01.jar data/cit-HepPh wic 10 > result/degree-hepPh-wic-k10.out
java -jar degree-p0.01.jar data/cit-HepPh wic 5 > result/degree-hepPh-wic-k5.out
java -jar degree-p0.01.jar data/cit-HepPh wic 1 > result/degree-hepPh-wic-k1.out
java -jar degree-p0.01.jar data/cit-HepPh uic 50 > result/degree-hepPh-uic-k50.out
java -jar degree-p0.01.jar data/cit-HepPh uic 45 > result/degree-hepPh-uic-k45.out
java -jar degree-p0.01.jar data/cit-HepPh uic 40 > result/degree-hepPh-uic-k40.out
java -jar degree-p0.01.jar data/cit-HepPh uic 35 > result/degree-hepPh-uic-k35.out
java -jar degree-p0.01.jar data/cit-HepPh uic 30 > result/degree-hepPh-uic-k30.out
java -jar degree-p0.01.jar data/cit-HepPh uic 25 > result/degree-hepPh-uic-k25.out
java -jar degree-p0.01.jar data/cit-HepPh uic 20 > result/degree-hepPh-uic-k20.out
java -jar degree-p0.01.jar data/cit-HepPh uic 15 > result/degree-hepPh-uic-k15.out
java -jar degree-p0.01.jar data/cit-HepPh uic 10 > result/degree-hepPh-uic-k10.out
java -jar degree-p0.01.jar data/cit-HepPh uic 5 > result/degree-hepPh-uic-k5.out
java -jar degree-p0.01.jar data/cit-HepPh uic 1 > result/degree-hepPh-uic-k1.out
