java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 50 > result/res-facebook-wic-k50.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 45 > result/res-facebook-wic-k45.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 40 > result/res-facebook-wic-k40.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 35 > result/res-facebook-wic-k35.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 30 > result/res-facebook-wic-k30.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 25 > result/res-facebook-wic-k25.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 20 > result/res-facebook-wic-k20.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 15 > result/res-facebook-wic-k15.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 10 > result/res-facebook-wic-k10.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 5 > result/res-facebook-wic-k5.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt wic 1 > result/res-facebook-wic-k1.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 50 > result/res-facebook-uic-k50.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 45 > result/res-facebook-uic-k45.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 40 > result/res-facebook-uic-k40.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 35 > result/res-facebook-uic-k35.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 30 > result/res-facebook-uic-k30.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 25 > result/res-facebook-uic-k25.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 20 > result/res-facebook-uic-k20.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 15 > result/res-facebook-uic-k15.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 10 > result/res-facebook-uic-k10.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 5 > result/res-facebook-uic-k5.out
java -jar jar/res-p0.01.jar data/facebook_combined.txt uic 1 > result/res-facebook-uic-k1.out
